services:
  cerveceria-charles-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cerveceria-charles-web
    restart: unless-stopped
    networks:
      - core_default

networks:
  core_default:
    external: true